default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sjwbot_dev

test:
  <<: *default
  database: sjwbot_test

production:
  <<: *default
  database: sjwbot_prod
